version: '3'
services:
  mysql-db:
    image: mysql:8.0
    hostname: mysql-db
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  mongo_db:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017

volumes:
  my-db-volume:

